on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demo1555.azurecr.io
        username: ${{ secrets.acr_demo1555_username }}
        password: ${{ secrets.acr_demo1555_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ubuntu" -f  "ubuntu/Dockerfile" -t demo1555.azurecr.io/demo:${{ github.sha }} --label dockerfile-path=ubuntu/Dockerfile
        docker push demo1555.azurecr.io/demo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo9e80 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo9e80`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo9e80
        container-registry-url: demo1555.azurecr.io
        container-registry-username: ${{ secrets.acr_demo1555_username }}
        container-registry-password: ${{ secrets.acr_demo1555_password }}
        secret-name: demodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demo9e80
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          demo1555.azurecr.io/demo:${{ github.sha }}
        imagepullsecrets: |
          demodockerauth
